server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TEST?characterEncoding=utf8&amp;useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    timeout: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hdx.dao
  typeAliasesPackage: com.springboot.bean



